### ISSUE TITLE
프로그래머스 1단계

### ISSUE THREAD

**Issue by AI-Dev-Lex-Kim** [ai-creatv/algorithm_FDS17#1]
[프로그래머스 1단계](https://github.com/Alex-Eojin/-TIL/blob/master/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98/%EC%88%AB%EC%9E%90%20%EB%B0%B0%EC%97%B4%EB%A7%8C%EB%93%A4%EA%B8%B0%20%2C%EC%A7%81%EC%82%AC%EA%B0%81%ED%98%95%20%EB%A7%8C%EB%93%A4%EA%B8%B0.md)

**Comment by Kim-Jaemin420** [comment]
# 프로그래머스 스킬체크 1단계  

## 예산  
```js
function solution(d, budget) {
  d.sort((a, b) => a - b);

  while (d.reduce((a, b) => (a + b), 0) > budget) d.pop();

  return d.length;
}
```
정렬된 배열 d의 요소들을 누적해서 합한 값이 예산 이상이라면 pop한다.

## 수박수박수박수박수박수?
```js
function solution(n) {
   let answer = '';
  for (let i = 0; i < n; i++) {
    i % 2 ? (answer += '박') : (answer += '수');
  }
  return answer;
}
```
짝수면 수, 홀수면 박!

<img width="800" alt="스크린샷 2020-12-28 오후 7 21 12" src="https://user-images.githubusercontent.com/61978339/103207507-db8bb480-4941-11eb-86c2-1ffe69a9c1f6.png">

**Comment by Kim-Jaemin420** [comment]
<a href="https://github.com/Kim-Jaemin420/Programmers/blob/master/Algorithm_homework/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4%20%EC%8A%A4%ED%82%AC%EC%B2%B4%ED%81%AC%20%EB%A0%88%EB%B2%A81.md">프로그래머스 스킬체크 레벨1</a>

**Comment by jungjh123456** [comment]
[프로그래머스 1단계](https://github.com/jungjh123456/homework/blob/master/algorithem.md)

**Comment by ai-creatv** [comment]
깔끔하게 잘 구현해서 레벨1을 잘 획득해 주셨네요! :) 수고하셨습니다.
