### ISSUE TITLE
프로그래머스 1단계

### ISSUE THREAD

**Issue by jungjh123456** [ai-creatv/algorithm_FDS17#2]
[프로그래머스 1단계](https://github.com/jungjh123456/homework/blob/master/algorithem.md)

**Comment by ai-creatv** [comment]
깔끔하게 잘 구현해서 레벨1을 잘 획득해 주셨네요! :)

- 1번 문제에서 else if는 else만 써도 될 것 같습니다.
- 2번 문제에서는 0은 정의하지 않고 -1, 1만 정의해도 소팅이 잘 됩니다. (두 값이 같은 경우에는 순서가 관계 없으므로)

수고하셨습니다.
