### ISSUE TITLE
프로그래머스 스킬 체크 1단계

### ISSUE THREAD

**Issue by thalassophilia** [ai-creatv/algorithm_FDS17#3]
[프로그래머스 스킬 체크 1단계](https://github.com/Kim-Jaemin420/Programmers/blob/master/Algorithm_homework/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4%20%EC%8A%A4%ED%82%AC%EC%B2%B4%ED%81%AC%20%EB%A0%88%EB%B2%A81.md)

**Comment by ai-creatv** [comment]
깔끔하게 잘 구현해서 레벨1을 잘 획득해 주셨네요! :)

- 1번 문제에서 sort는 기본 sort와 같으니 그냥 sort()만 쓰는 것이 더 좋습니다.
- reduce를 쓴 것은 좋지만, 매번 새로 reduce를 하니 불필요한 O(n) 연산이 들어갑니다. pop된것을 빼주는 형식으로 업데이트 하는 것이 더 좋습니다 :)

수고하셨습니다.
