### ISSUE TITLE
프로그래머스 스킬 체크 1단계

### ISSUE THREAD

**Issue by hanseul-lee** [ai-creatv/algorithm_FDS17#5]
[프로그래머스 스킬 체크 1단계](https://github.com/hanseul-lee/algorithm_FDS17/blob/master/5_Homeworks/1/homework_01.md)

**Comment by ai-creatv** [comment]
깔끔하게 잘 구현해서 레벨1을 잘 획득해 주셨네요! :)

- 1번은 유클리드 호제법을 이용해서 잘 구현해 주셨네요!
- 2번은 구현해주신 방법에서는 복잡도는 sort()에 의해서 O(NlogN)입니다. 나중에 배울 Hash Table에 속하는 Map 객체를 이용하면 O(N)으로 해결 가능하니, 참고해주세요 :)

수고하셨습니다.
