### ISSUE TITLE
프로그래머스 스킬 체크 1단계

### ISSUE THREAD

**Issue by ghost** [ai-creatv/algorithm_FDS17#6]
[프로그래머스 스킬 체크 1단계](https://github.com/dongchan-K/TIL/blob/master/JavaScript/example/Algorithm%20Homework1.md)

**Comment by ai-creatv** [comment]
깔끔하게 잘 구현해서 레벨1을 잘 획득해 주셨네요! :)

- 다만, 문제의 스크린샷을 업로드하시면 저작권상의 문제가 될 수 있으니 삭제해주세요 :)

수고하셨습니다.
