### ISSUE TITLE
프로그래머스 1단계

### ISSUE THREAD

**Issue by park-moen** [ai-creatv/algorithm_FDS17#7]
![image](https://user-images.githubusercontent.com/57402711/103482239-13539a00-4e23-11eb-896f-94954281bbe1.png)

![image](https://user-images.githubusercontent.com/57402711/103482265-3da55780-4e23-11eb-8ccc-dbc5d121734d.png)

![image](https://user-images.githubusercontent.com/57402711/103482282-544bae80-4e23-11eb-9172-88be0ecc35b2.png)

https://github.com/park-moen/algorithm/blob/main/app.js

**Comment by ai-creatv** [comment]
깔끔하게 잘 구현해서 레벨1을 잘 획득해 주셨네요! :) 수고하셨습니다.
